'use client'

/**
 * DocSearch — Pagefind-powered search overlay.
 *
 * Usage:
 *   - Click the search button in the header, or
 *   - Press ⌘K (macOS) / Ctrl+K (Windows/Linux)
 *
 * The Pagefind index is generated by `postbuild` (see package.json).
 * The @pagefind/default-ui bundle is loaded lazily on first open to keep
 * the main bundle small.
 *
 * Closes #182
 */

import React, { useCallback, useEffect, useRef, useState } from 'react'

// ---------------------------------------------------------------------------
// Types — @pagefind/default-ui doesn't ship its own .d.ts yet
// ---------------------------------------------------------------------------
interface PagefindUI {
  new (options: { element: string | HTMLElement; showImages?: boolean; resetStyles?: boolean }): void
}

declare global {
  interface Window {
    PagefindUI?: PagefindUI
  }
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------
export function DocSearch() {
  const [open, setOpen] = useState(false)
  const [loaded, setLoaded] = useState(false)
  const containerRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement | null>(null)

  // Lazily initialise Pagefind UI when the modal first opens
  const initPagefind = useCallback(async () => {
    if (loaded) return
    try {
      // @pagefind/default-ui ships its own CSS and JS from /pagefind/ (output of postbuild)
      const cssLink = document.createElement('link')
      cssLink.rel = 'stylesheet'
      cssLink.href = '/pagefind/pagefind-ui.css'
      document.head.appendChild(cssLink)

      const script = document.createElement('script')
      script.src = '/pagefind/pagefind-ui.js'
      script.onload = () => {
        if (containerRef.current && window.PagefindUI) {
          new window.PagefindUI({
            element: containerRef.current,
            showImages: false,
            resetStyles: false,
          })
          setLoaded(true)
          // Auto-focus the search input after Pagefind renders it
          requestAnimationFrame(() => {
            const input = containerRef.current?.querySelector<HTMLInputElement>('input')
            if (input) {
              inputRef.current = input
              input.focus()
            }
          })
        }
      }
      document.body.appendChild(script)
    } catch (err) {
      console.error('[DocSearch] Failed to load Pagefind UI', err)
    }
  }, [loaded])

  const openModal = useCallback(() => {
    setOpen(true)
    initPagefind()
  }, [initPagefind])

  const closeModal = useCallback(() => {
    setOpen(false)
  }, [])

  // ⌘K / Ctrl+K global shortcut
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault()
        if (open) {
          closeModal()
        } else {
          openModal()
        }
      }
      if (e.key === 'Escape' && open) {
        closeModal()
      }
    }
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [open, openModal, closeModal])

  // Re-focus input when modal is already loaded and re-opened
  useEffect(() => {
    if (open && loaded) {
      requestAnimationFrame(() => {
        inputRef.current?.focus()
      })
    }
  }, [open, loaded])

  return (
    <>
      {/* ── Trigger button ───────────────────────────────────────────────── */}
      <button
        id="veil-search-trigger"
        aria-label="Search documentation"
        title="Search (⌘K)"
        onClick={openModal}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '6px',
          padding: '4px 10px',
          borderRadius: '6px',
          border: '1px solid rgba(253, 218, 36, 0.25)',
          background: 'rgba(255,255,255,0.04)',
          color: '#D6D2C4',
          fontFamily: 'Inter, sans-serif',
          fontSize: '0.8rem',
          cursor: 'pointer',
          transition: 'border-color 0.15s, background 0.15s',
          whiteSpace: 'nowrap',
        }}
        onMouseEnter={(e) => {
          const btn = e.currentTarget
          btn.style.borderColor = 'rgba(253, 218, 36, 0.6)'
          btn.style.background = 'rgba(253, 218, 36, 0.07)'
        }}
        onMouseLeave={(e) => {
          const btn = e.currentTarget
          btn.style.borderColor = 'rgba(253, 218, 36, 0.25)'
          btn.style.background = 'rgba(255,255,255,0.04)'
        }}
      >
        {/* Magnifier icon */}
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <circle cx="11" cy="11" r="8" />
          <line x1="21" y1="21" x2="16.65" y2="16.65" />
        </svg>
        Search
        <kbd
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            padding: '1px 5px',
            borderRadius: '4px',
            border: '1px solid rgba(214, 210, 196, 0.3)',
            background: 'rgba(255,255,255,0.06)',
            fontFamily: 'Inter, sans-serif',
            fontSize: '0.7rem',
            color: '#D6D2C4',
            lineHeight: 1.4,
          }}
        >
          ⌘K
        </kbd>
      </button>

      {/* ── Backdrop + modal ─────────────────────────────────────────────── */}
      {open && (
        <div
          id="veil-search-backdrop"
          role="dialog"
          aria-modal="true"
          aria-label="Search"
          style={{
            position: 'fixed',
            inset: 0,
            zIndex: 9999,
            display: 'flex',
            alignItems: 'flex-start',
            justifyContent: 'center',
            paddingTop: '80px',
            background: 'rgba(15, 15, 15, 0.75)',
            backdropFilter: 'blur(6px)',
          }}
          onClick={(e) => {
            if (e.target === e.currentTarget) closeModal()
          }}
        >
          <div
            id="veil-search-modal"
            style={{
              width: '100%',
              maxWidth: '640px',
              margin: '0 16px',
              borderRadius: '12px',
              border: '1px solid rgba(253, 218, 36, 0.2)',
              background: '#181818',
              boxShadow: '0 24px 64px rgba(0,0,0,0.6)',
              overflow: 'hidden',
            }}
          >
            {/* Pagefind mounts itself into this div */}
            <div
              ref={containerRef}
              id="veil-pagefind-container"
              style={{ padding: '12px' }}
            />

            <div
              style={{
                display: 'flex',
                justifyContent: 'flex-end',
                padding: '8px 16px',
                borderTop: '1px solid rgba(255,255,255,0.06)',
              }}
            >
              <span style={{ fontSize: '0.75rem', color: '#666', fontFamily: 'Inter, sans-serif' }}>
                Press{' '}
                <kbd
                  style={{
                    padding: '1px 5px',
                    borderRadius: '4px',
                    border: '1px solid #333',
                    background: '#222',
                    fontFamily: 'Inter, sans-serif',
                  }}
                >
                  Esc
                </kbd>{' '}
                to close
              </span>
            </div>
          </div>
        </div>
      )}

      {/* ── Pagefind UI style overrides (injected once) ───────────────────── */}
      <style>{`
        /* Match Veil's gold accent */
        .pagefind-ui__search-input {
          background: #111 !important;
          color: #F6F7F8 !important;
          border: 1px solid rgba(253, 218, 36, 0.35) !important;
          border-radius: 8px !important;
          font-family: 'Inter', sans-serif !important;
        }
        .pagefind-ui__search-input:focus {
          border-color: #FDDA24 !important;
          outline: none !important;
          box-shadow: 0 0 0 2px rgba(253, 218, 36, 0.15) !important;
        }
        .pagefind-ui__results-area {
          background: transparent !important;
        }
        .pagefind-ui__result {
          border-bottom: 1px solid rgba(255,255,255,0.06) !important;
        }
        .pagefind-ui__result-title {
          color: #FDDA24 !important;
          font-family: 'Lora', Georgia, serif !important;
          font-style: italic !important;
        }
        .pagefind-ui__result-excerpt {
          color: #D6D2C4 !important;
          font-family: 'Inter', sans-serif !important;
          font-size: 0.85rem !important;
        }
        .pagefind-ui__result-link:hover .pagefind-ui__result-title {
          text-decoration: underline !important;
        }
        .pagefind-ui__message {
          color: #888 !important;
          font-family: 'Inter', sans-serif !important;
        }
        mark {
          background: rgba(253, 218, 36, 0.35) !important;
          color: inherit !important;
          border-radius: 2px;
          padding: 0 2px;
        }
      `}</style>
    </>
  )
}
