import { ExpoConfig, ConfigContext } from 'expo/config';

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: config.name ?? 'Veil',
  slug: config.slug ?? 'veil-mobile',
  extra: {
    ...config.extra,
    NEXT_PUBLIC_HORIZON_URL: process.env.NEXT_PUBLIC_HORIZON_URL || process.env.EXPO_PUBLIC_HORIZON_URL,
    NEXT_PUBLIC_SOROBAN_RPC_URL: process.env.NEXT_PUBLIC_SOROBAN_RPC_URL || process.env.EXPO_PUBLIC_SOROBAN_RPC_URL,
    NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL || process.env.EXPO_PUBLIC_RPC_URL,
    NEXT_PUBLIC_FACTORY_CONTRACT_ID_TESTNET:
      process.env.NEXT_PUBLIC_FACTORY_CONTRACT_ID_TESTNET || process.env.EXPO_PUBLIC_FACTORY_CONTRACT_ID_TESTNET,
    NEXT_PUBLIC_FACTORY_CONTRACT_ID:
      process.env.NEXT_PUBLIC_FACTORY_CONTRACT_ID || process.env.EXPO_PUBLIC_FACTORY_CONTRACT_ID,
    NEXT_PUBLIC_MAINNET_RPC_URL: process.env.NEXT_PUBLIC_MAINNET_RPC_URL || process.env.EXPO_PUBLIC_MAINNET_RPC_URL,
    NEXT_PUBLIC_FACTORY_CONTRACT_ID_MAINNET:
      process.env.NEXT_PUBLIC_FACTORY_CONTRACT_ID_MAINNET || process.env.EXPO_PUBLIC_FACTORY_CONTRACT_ID_MAINNET,
    NEXT_PUBLIC_NETWORK: process.env.NEXT_PUBLIC_NETWORK || process.env.EXPO_PUBLIC_NETWORK,

    EXPO_PUBLIC_HORIZON_URL: process.env.EXPO_PUBLIC_HORIZON_URL || process.env.NEXT_PUBLIC_HORIZON_URL,
    EXPO_PUBLIC_SOROBAN_RPC_URL: process.env.EXPO_PUBLIC_SOROBAN_RPC_URL || process.env.NEXT_PUBLIC_SOROBAN_RPC_URL,
    EXPO_PUBLIC_RPC_URL: process.env.EXPO_PUBLIC_RPC_URL || process.env.NEXT_PUBLIC_RPC_URL,
    EXPO_PUBLIC_FACTORY_CONTRACT_ID_TESTNET:
      process.env.EXPO_PUBLIC_FACTORY_CONTRACT_ID_TESTNET || process.env.NEXT_PUBLIC_FACTORY_CONTRACT_ID_TESTNET,
    EXPO_PUBLIC_FACTORY_CONTRACT_ID:
      process.env.EXPO_PUBLIC_FACTORY_CONTRACT_ID || process.env.NEXT_PUBLIC_FACTORY_CONTRACT_ID,
    EXPO_PUBLIC_MAINNET_RPC_URL: process.env.EXPO_PUBLIC_MAINNET_RPC_URL || process.env.NEXT_PUBLIC_MAINNET_RPC_URL,
    EXPO_PUBLIC_FACTORY_CONTRACT_ID_MAINNET:
      process.env.EXPO_PUBLIC_FACTORY_CONTRACT_ID_MAINNET || process.env.NEXT_PUBLIC_FACTORY_CONTRACT_ID_MAINNET,
    EXPO_PUBLIC_NETWORK: process.env.EXPO_PUBLIC_NETWORK || process.env.NEXT_PUBLIC_NETWORK,
  },
});
